plugins {
    id 'java'
}

group = 'ru.levitsky'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.auto.service:auto-service:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
    implementation 'com.squareup:javapoet:1.13.0'

    testImplementation 'com.google.testing.compile:compile-testing:0.21.0'
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnitPlatform()
}